#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
HEADER="$ROOT/firmware/keyboards/pico_4x4/profile_switching.h"
DEFAULT_KEYMAP="$ROOT/firmware/keyboards/pico_4x4/keymaps/default/keymap.c"
VIA_KEYMAP="$ROOT/firmware/keyboards/pico_4x4/keymaps/via/keymap.c"
CONFIG="$ROOT/firmware/keyboards/pico_4x4/config.h"
RULES="$ROOT/firmware/keyboards/pico_4x4/rules.mk"

test -f "$HEADER"
grep -Fq 'L_WIN_M1' "$HEADER"
grep -Fq 'L_WIN_M2' "$HEADER"
grep -Fq 'L_LINUX_M1' "$HEADER"
grep -Fq 'L_LINUX_M2' "$HEADER"
grep -Fq 'L_WIN_FN' "$HEADER"
grep -Fq 'L_LINUX_FN' "$HEADER"
grep -Fq 'L_WIN_M2_FN' "$HEADER"
grep -Fq 'M_TOGGLE = SAFE_RANGE' "$HEADER"
grep -Fq 'OS_TOGGLE' "$HEADER"
grep -Fq 'eeconfig_read_user()' "$HEADER"
grep -Fq 'eeconfig_update_user' "$HEADER"
grep -Fq 'get_mods() & MOD_MASK_CTRL' "$HEADER"
grep -Fq 'layer_move' "$HEADER"

for keymap in "$DEFAULT_KEYMAP" "$VIA_KEYMAP"; do
    grep -Fq '#include "../../profile_switching.h"' "$keymap"
    grep -Fq '[L_WIN_M1] = PICO_4X4_WINDOWS_M1_LAYER' "$keymap"
    grep -Fq '[L_WIN_M2] = PICO_4X4_WINDOWS_M2_LAYER' "$keymap"
    grep -Fq '[L_LINUX_M1] = PICO_4X4_LINUX_PROFILE_LAYER' "$keymap"
    grep -Fq '[L_LINUX_M2] = PICO_4X4_LINUX_PROFILE_LAYER' "$keymap"
    grep -Fq '[L_WIN_FN] = PICO_4X4_WINDOWS_FN_LAYER' "$keymap"
    grep -Fq '[L_LINUX_FN] = PICO_4X4_LINUX_FN_LAYER' "$keymap"
    grep -Fq '[L_WIN_M2_FN] = PICO_4X4_WINDOWS_M2_FN_LAYER' "$keymap"
done

grep -Fq '#define PICO_4X4_WINDOWS_M1_LAYER PICO_4X4_PROFILE_LAYER(L_WIN_FN)' "$HEADER"
grep -Fq '#define PICO_4X4_WINDOWS_M2_LAYER PICO_4X4_PROFILE_LAYER(L_WIN_M2_FN)' "$HEADER"
grep -Fq '#define PICO_4X4_WINDOWS_M2_FN_LAYER' "$HEADER"
grep -Fq '#define PICO_4X4_LINUX_PROFILE_LAYER PICO_4X4_PROFILE_LAYER(L_LINUX_FN)' "$HEADER"
grep -Eq 'LCA\(KC_1\),[[:space:]]+LCA\(KC_5\),[[:space:]]+OS_TOGGLE,[[:space:]]+KC_TRNS' "$HEADER"
grep -Eq 'LCA\(KC_2\),[[:space:]]+LCA\(KC_6\),[[:space:]]+MS_LEFT,[[:space:]]+KC_LCTL' "$HEADER"
grep -Eq 'LCA\(KC_3\),[[:space:]]+MS_UP,[[:space:]]+MS_DOWN,[[:space:]]+MS_BTN1' "$HEADER"
grep -Eq 'LCA\(KC_4\),[[:space:]]+LCA\(KC_7\),[[:space:]]+MS_RGHT,[[:space:]]+MS_BTN2' "$HEADER"
grep -Eq 'KC_4,[[:space:]]+KC_BSPC,[[:space:]]+KC_RGHT,[[:space:]]+KC_ENT' "$HEADER"
grep -Fq 'KC_TRNS, KC_TRNS, OS_TOGGLE, KC_TRNS' "$HEADER"
grep -Eq 'KC_TRNS,[[:space:]]+KC_TRNS,[[:space:]]+MS_LEFT,[[:space:]]+KC_LCTL' "$HEADER"
grep -Eq 'KC_TRNS,[[:space:]]+MS_UP,[[:space:]]+MS_DOWN,[[:space:]]+KC_TRNS' "$HEADER"
grep -Eq 'KC_TRNS,[[:space:]]+KC_TRNS,[[:space:]]+MS_RGHT,[[:space:]]+KC_TRNS' "$HEADER"
grep -Eq 'LALT\(KC_TAB\),[[:space:]]+LGUI\(KC_E\),[[:space:]]+M_TOGGLE,[[:space:]]+MO\(L_WIN_M2_FN\)' "$HEADER"
grep -Eq 'LGUI\(KC_TAB\),[[:space:]]+LGUI\(KC_R\),[[:space:]]+LGUI\(KC_LEFT\),[[:space:]]+KC_LCTL' "$HEADER"
grep -Eq 'LGUI\(KC_D\),[[:space:]]+LGUI\(KC_UP\),[[:space:]]+LGUI\(KC_DOWN\),[[:space:]]+KC_ESC' "$HEADER"
grep -Eq 'LALT\(KC_F4\),[[:space:]]+LGUI\(KC_L\),[[:space:]]+LGUI\(KC_RGHT\),[[:space:]]+KC_ENT' "$HEADER"
grep -Eq 'LCTL\(KC_Z\),[[:space:]]+LCTL\(KC_V\),[[:space:]]+OS_TOGGLE,[[:space:]]+KC_TRNS' "$HEADER"
grep -Eq 'LCTL\(KC_Y\),[[:space:]]+LCTL\(KC_A\),[[:space:]]+LCTL\(KC_LEFT\),[[:space:]]+KC_LCTL' "$HEADER"
grep -Eq 'LCTL\(KC_X\),[[:space:]]+KC_HOME,[[:space:]]+KC_END,[[:space:]]+KC_ESC' "$HEADER"
grep -Eq 'LCTL\(KC_C\),[[:space:]]+LCTL\(KC_BSPC\),[[:space:]]+LCTL\(KC_RGHT\),[[:space:]]+KC_ENT' "$HEADER"
grep -Fq 'working_state &= ~((layer_state_t)1 << L_WIN_M2_FN);' "$HEADER"
grep -Fq '#define DYNAMIC_KEYMAP_LAYER_COUNT 7' "$CONFIG"
grep -Fq 'BOOTMAGIC_ENABLE = yes' "$RULES"
grep -Fq 'MOUSEKEY_ENABLE = yes' "$RULES"
